security:
  cors_origin_methods: CORS_ORIGIN_METHODS
  cors_origin_whitelist: CORS_ORIGIN_WHITELIST
  auth_whitelist: AUTH_WHITE_LIST
  auth_blacklist: AUTH_BLACK_LIST
idam:
  base_url: IDAM_BASE_URL
redis:
  host: REDIS_HOST
  port: REDIS_PORT
  password: REDIS_PASSWORD
  ssl: REDIS_SSL_ENABLED
  keyPrefix: REDIS_KEY_PREFIX
  activityTtlSec: REDIS_ACTIVITY_TTL
  userDetailsTtlSec: REDIS_USER_DETAILS_TTL
  socket:
    activityTtlSec: REDIS_SOCKET_ACTIVITY_TTL
    userDetailsTtlSec: REDIS_SOCKET_USER_DETAILS_TTL
cache:
  user_info_enabled: CACHE_USER_INFO_ENABLED
  user_info_ttl: CACHE_USER_INFO_TTL
  user_info_check_period: CACHE_USER_INFO_CHECK_PERIOD
app:
  requestTimeoutSec: APP_REQUEST_TIMEOUT
  storeCleanupCrontab: APP_STORE_CLEANUP_CRONTAB
appInsights:
  instrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY

secrets:
  ccd:
    activity-redis-password: REDIS_PASSWORD
    AppInsightsInstrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY
